export const products = [
  { id: 1, name: "Dragon Dogma", image: "./Images/product (1).jpg", price: 29.99, category: "Action" },
  { id: 2, name: "Dying Light", image: "./Images/product (2).jpg", price: 29.99, category: "Role Playing" },
  { id: 3, name: "Stray", image: "./Images/product (3).jpg", price: 29.99, category: "Open World" },
  { id: 4, name: "Elden Ring", image: "./Images/product (4).jpg", price: 49.99, category: "Action RPG" },
  { id: 5, name: "God of War", image: "./Images/product (5).jpg", price: 39.99, category: "Action" },
  { id: 6, name: "Horizon Forbidden West", image: "./Images/product (6).jpg", price: 59.99, category: "Open World" },
  { id: 7, name: "The Witcher 3", image: "./Images/product (7).jpg", price: 39.99, category: "Role Playing" },
  { id: 8, name: "Cyberpunk 2077", image: "./Images/product (8).jpg", price: 59.99, category: "Open World" },
  { id: 9, name: "Assassin's Creed Valhalla", image: "./Images/product (9).jpg", price: 49.99, category: "Action" },
  { id: 10, name: "Red Dead Redemption 2", image: "./Images/product (10).jpg", price: 59.99, category: "Open World" },
  { id: 11, name: "Minecraft", image: "./Images/product (11).jpg", price: 19.99, category: "Sandbox" },
  { id: 12, name: "Fortnite", image: "./Images/product (12).jpg", price: 0.00, category: "Battle Royale" },
  { id: 13, name: "Call of Duty: Warzone", image: "./Images/product (13).jpg", price: 0.00, category: "Shooter" },
  { id: 14, name: "FIFA 22", image: "./Images/product (14).jpg", price: 59.99, category: "Sports" },
  { id: 15, name: "NBA 2K21", image: "./Images/product (15).jpg", price: 59.99, category: "Sports" },
  { id: 16, name: "League of Legends", image: "./Images/product (16).jpg", price: 0.00, category: "MOBA" },
  
  // Repeating images from 1-16
  { id: 17, name: "Dark Souls III", image: "./Images/product (1).jpg", price: 49.99, category: "Action RPG" },
  { id: 18, name: "Bloodborne", image: "./Images/product (2).jpg", price: 39.99, category: "Action" },
  { id: 19, name: "Far Cry 6", image: "./Images/product (3).jpg", price: 59.99, category: "Shooter" },
  { id: 20, name: "Overwatch 2", image: "./Images/product (4).jpg", price: 39.99, category: "Shooter" },
  { id: 21, name: "GTA V", image: "./Images/product (5).jpg", price: 29.99, category: "Open World" },
  { id: 22, name: "Resident Evil Village", image: "./Images/product (6).jpg", price: 49.99, category: "Horror" },
  { id: 23, name: "Sekiro: Shadows Die Twice", image: "./Images/product (7).jpg", price: 39.99, category: "Action" },
  { id: 24, name: "Apex Legends", image: "./Images/product (8).jpg", price: 0.00, category: "Battle Royale" },
  { id: 25, name: "Valorant", image: "./Images/product (9).jpg", price: 0.00, category: "Shooter" },
  { id: 26, name: "Monster Hunter World", image: "./Images/product (10).jpg", price: 49.99, category: "Action RPG" },
  { id: 27, name: "Starfield", image: "./Images/product (11).jpg", price: 69.99, category: "Sci-Fi RPG" },
  { id: 28, name: "Diablo IV", image: "./Images/product (12).jpg", price: 59.99, category: "RPG" },
  { id: 29, name: "The Legend of Zelda: Breath of the Wild", image: "./Images/product (13).jpg", price: 59.99, category: "Adventure" },
  { id: 30, name: "Splatoon 3", image: "./Images/product (14).jpg", price: 49.99, category: "Shooter" },
  { id: 31, name: "Halo Infinite", image: "./Images/product (15).jpg", price: 59.99, category: "Shooter" },
  { id: 32, name: "Star Wars Jedi: Survivor", image: "./Images/product (16).jpg", price: 69.99, category: "Action RPG" }
];
